upstream django {
    server django_app:8000;
}
server {
    listen       80;
    server_name  _;
    charset utf-8;

    access_log /tmp/logs/nginx_access.log;
    error_log  /tmp/logs/nginx_error.log warn;

    location /static/ {
	    autoindex on;
        alias /static/;
    }

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://django;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
