# Generated by Django 5.2.3 on 2025-06-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address')),
                ('nickname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nickname')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Email verified at')),
                ('language', models.CharField(choices=[('sq', 'Albanian - Shqip'), ('ar', 'Arabic - عربي'), ('az', 'Azerbaijani - Azərbaycan'), ('eu', 'Basque - Euskara'), ('bn', 'Bengali - বাংলা'), ('bg', 'Bulgarian - Български'), ('ca', 'Catalan - Català'), ('zh-hans', 'Chinese (Simplified) - 中文'), ('zh-hant', 'Chinese (Traditional) - 繁體中文'), ('hr', 'Croatian - Hrvatski'), ('cs', 'Czech - Čeština'), ('da', 'Danish - Dansk'), ('nl', 'Dutch - Nederlands'), ('en', 'English'), ('eo', 'Esperanto - Esperanto'), ('et', 'Estonian - Eesti'), ('fi', 'Finnish - Suomi'), ('fr', 'French - Français'), ('gl', 'Galician - Galego'), ('de', 'German - Deutsch'), ('el', 'Greek - Ελληνικά'), ('he', 'Hebrew - עברית'), ('hi', 'Hindi - हिन्दी'), ('hu', 'Hungarian - Magyar'), ('is', 'Icelandic - Íslenska'), ('id', 'Indonesian - Bahasa Indonesia'), ('ga', 'Irish - Gaeilge'), ('it', 'Italian - Italiano'), ('ja', 'Japanese - 日本語'), ('ko', 'Korean - 한국어'), ('lv', 'Latvian - Latviešu'), ('lt', 'Lithuanian - Lietuvių'), ('ms', 'Malay - Bahasa Melayu'), ('nb', 'Norwegian - Norsk Bokmål'), ('fa', 'Persian - فارسی'), ('pl', 'Polish - Polski'), ('pt', 'Portuguese - Português'), ('pt-br', 'Portuguese (Brazil) - Português (Brasil)'), ('ro', 'Romanian - Română'), ('ru', 'Russian - Русский'), ('sk', 'Slovak - Slovenčina'), ('sl', 'Slovenian - Slovenščina'), ('es', 'Spanish - Español'), ('sv', 'Swedish - Svenska'), ('tl', 'Tagalog - Tagalog'), ('th', 'Thai - ไทย'), ('tr', 'Turkish - Türkçe'), ('uk', 'Ukrainian - Українська'), ('ur', 'Urdu - اردو')], default='en', max_length=10, verbose_name='Preferred language')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
