# Generated by Django 5.2.3 on 2025-06-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usersetting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="language",
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="key",
            field=models.CharField(
                choices=[("language", "Language"), ("theme_mode", "Theme Mode"), ("sort_mode", "Sort Mode")],
                max_length=50,
            ),
        ),
    ]
