# Generated by Django 5.2.3 on 2025-06-15 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the energy value per 100g or 100ml of the product.', max_digits=6, null=True, verbose_name='Calories per 100g/ml')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_language', models.CharField(choices=[('sq', 'Albanian - Shqip'), ('ar', 'Arabic - عربي'), ('az', 'Azerbaijani - Azərbaycan'), ('eu', 'Basque - Euskara'), ('bn', 'Bengali - বাংলা'), ('bg', 'Bulgarian - Български'), ('ca', 'Catalan - Català'), ('zh-hans', 'Chinese (Simplified) - 中文'), ('zh-hant', 'Chinese (Traditional) - 繁體中文'), ('hr', 'Croatian - Hrvatski'), ('cs', 'Czech - Čeština'), ('da', 'Danish - Dansk'), ('nl', 'Dutch - Nederlands'), ('en', 'English'), ('eo', 'Esperanto - Esperanto'), ('et', 'Estonian - Eesti'), ('fi', 'Finnish - Suomi'), ('fr', 'French - Français'), ('gl', 'Galician - Galego'), ('de', 'German - Deutsch'), ('el', 'Greek - Ελληνικά'), ('he', 'Hebrew - עברית'), ('hi', 'Hindi - हिन्दी'), ('hu', 'Hungarian - Magyar'), ('is', 'Icelandic - Íslenska'), ('id', 'Indonesian - Bahasa Indonesia'), ('ga', 'Irish - Gaeilge'), ('it', 'Italian - Italiano'), ('ja', 'Japanese - 日本語'), ('ko', 'Korean - 한국어'), ('lv', 'Latvian - Latviešu'), ('lt', 'Lithuanian - Lietuvių'), ('ms', 'Malay - Bahasa Melayu'), ('nb', 'Norwegian - Norsk Bokmål'), ('fa', 'Persian - فارسی'), ('pl', 'Polish - Polski'), ('pt', 'Portuguese - Português'), ('pt-br', 'Portuguese (Brazil) - Português (Brasil)'), ('ro', 'Romanian - Română'), ('ru', 'Russian - Русский'), ('sk', 'Slovak - Slovenčina'), ('sl', 'Slovenian - Slovenščina'), ('es', 'Spanish - Español'), ('sv', 'Swedish - Svenska'), ('tl', 'Tagalog - Tagalog'), ('th', 'Thai - ไทย'), ('tr', 'Turkish - Türkçe'), ('uk', 'Ukrainian - Українська'), ('ur', 'Urdu - اردو')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('ml', 'milliliter'), ('l', 'liter'), ('pcs', 'piece'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('cup', 'cup')], max_length=10)),
            ],
            options={
                'verbose_name': 'Recipe ingredient',
                'verbose_name_plural': 'Recipe ingredients',
            },
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Recipe tag',
                'verbose_name_plural': 'Recipe tags',
            },
        ),
        migrations.CreateModel(
            name='RecipeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('sq', 'Albanian - Shqip'), ('ar', 'Arabic - عربي'), ('az', 'Azerbaijani - Azərbaycan'), ('eu', 'Basque - Euskara'), ('bn', 'Bengali - বাংলা'), ('bg', 'Bulgarian - Български'), ('ca', 'Catalan - Català'), ('zh-hans', 'Chinese (Simplified) - 中文'), ('zh-hant', 'Chinese (Traditional) - 繁體中文'), ('hr', 'Croatian - Hrvatski'), ('cs', 'Czech - Čeština'), ('da', 'Danish - Dansk'), ('nl', 'Dutch - Nederlands'), ('en', 'English'), ('eo', 'Esperanto - Esperanto'), ('et', 'Estonian - Eesti'), ('fi', 'Finnish - Suomi'), ('fr', 'French - Français'), ('gl', 'Galician - Galego'), ('de', 'German - Deutsch'), ('el', 'Greek - Ελληνικά'), ('he', 'Hebrew - עברית'), ('hi', 'Hindi - हिन्दी'), ('hu', 'Hungarian - Magyar'), ('is', 'Icelandic - Íslenska'), ('id', 'Indonesian - Bahasa Indonesia'), ('ga', 'Irish - Gaeilge'), ('it', 'Italian - Italiano'), ('ja', 'Japanese - 日本語'), ('ko', 'Korean - 한국어'), ('lv', 'Latvian - Latviešu'), ('lt', 'Lithuanian - Lietuvių'), ('ms', 'Malay - Bahasa Melayu'), ('nb', 'Norwegian - Norsk Bokmål'), ('fa', 'Persian - فارسی'), ('pl', 'Polish - Polski'), ('pt', 'Portuguese - Português'), ('pt-br', 'Portuguese (Brazil) - Português (Brasil)'), ('ro', 'Romanian - Română'), ('ru', 'Russian - Русский'), ('sk', 'Slovak - Slovenčina'), ('sl', 'Slovenian - Slovenščina'), ('es', 'Spanish - Español'), ('sv', 'Swedish - Svenska'), ('tl', 'Tagalog - Tagalog'), ('th', 'Thai - ไทย'), ('tr', 'Turkish - Türkçe'), ('uk', 'Ukrainian - Українська'), ('ur', 'Urdu - اردو')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Recipe translation',
                'verbose_name_plural': 'Recipe translations',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IngredientTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('sq', 'Albanian - Shqip'), ('ar', 'Arabic - عربي'), ('az', 'Azerbaijani - Azərbaycan'), ('eu', 'Basque - Euskara'), ('bn', 'Bengali - বাংলা'), ('bg', 'Bulgarian - Български'), ('ca', 'Catalan - Català'), ('zh-hans', 'Chinese (Simplified) - 中文'), ('zh-hant', 'Chinese (Traditional) - 繁體中文'), ('hr', 'Croatian - Hrvatski'), ('cs', 'Czech - Čeština'), ('da', 'Danish - Dansk'), ('nl', 'Dutch - Nederlands'), ('en', 'English'), ('eo', 'Esperanto - Esperanto'), ('et', 'Estonian - Eesti'), ('fi', 'Finnish - Suomi'), ('fr', 'French - Français'), ('gl', 'Galician - Galego'), ('de', 'German - Deutsch'), ('el', 'Greek - Ελληνικά'), ('he', 'Hebrew - עברית'), ('hi', 'Hindi - हिन्दी'), ('hu', 'Hungarian - Magyar'), ('is', 'Icelandic - Íslenska'), ('id', 'Indonesian - Bahasa Indonesia'), ('ga', 'Irish - Gaeilge'), ('it', 'Italian - Italiano'), ('ja', 'Japanese - 日本語'), ('ko', 'Korean - 한국어'), ('lv', 'Latvian - Latviešu'), ('lt', 'Lithuanian - Lietuvių'), ('ms', 'Malay - Bahasa Melayu'), ('nb', 'Norwegian - Norsk Bokmål'), ('fa', 'Persian - فارسی'), ('pl', 'Polish - Polski'), ('pt', 'Portuguese - Português'), ('pt-br', 'Portuguese (Brazil) - Português (Brasil)'), ('ro', 'Romanian - Română'), ('ru', 'Russian - Русский'), ('sk', 'Slovak - Slovenčina'), ('sl', 'Slovenian - Slovenščina'), ('es', 'Spanish - Español'), ('sv', 'Swedish - Svenska'), ('tl', 'Tagalog - Tagalog'), ('th', 'Thai - ไทย'), ('tr', 'Turkish - Türkçe'), ('uk', 'Ukrainian - Українська'), ('ur', 'Urdu - اردو')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cookbook.ingredient')),
            ],
            options={
                'verbose_name': 'Ingredient translation',
                'verbose_name_plural': 'Ingredient translations',
            },
        ),
    ]
