# Generated by Django 5.2.3 on 2025-06-15 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.ingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cookbook.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='cookbook.recipetag'),
        ),
        migrations.AddField(
            model_name='recipetranslation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cookbook.recipe'),
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cookbook.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredienttranslation',
            unique_together={('ingredient', 'language')},
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['ingredient'], name='cookbook_re_ingredi_ce9c97_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['recipe'], name='cookbook_re_recipe__e67a9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author', 'title'], name='cookbook_re_author__4d859f_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['title'], name='cookbook_re_title_3247db_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['created_at'], name='cookbook_re_created_a1392b_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_recipe_title_per_author'),
        ),
        migrations.AlterUniqueTogether(
            name='recipetranslation',
            unique_together={('recipe', 'language')},
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('recipe', 'order'), name='unique_order_per_recipe'),
        ),
    ]
