# Generated by Django 5.2.3 on 2025-06-15 09:39

from django.db import migrations

PREDEFINED_TAGS = {
    "healthy": {
        "name": "Healthy lifestyle",
        "description": "Low calorie, fiber rich",
    },
    "quick": {
        "name": "Quick",
        "description": "Prepares in 15–30 minutes",
    },
    "cheap": {
        "name": "Cheap",
        "description": "Affordable ingredients",
    },
    "holiday": {
        "name": "Holiday",
        "description": "Suitable for special occasions",
    },
    "vegan": {
        "name": "Vegan",
        "description": "No animal products",
    },
    "vegetarian": {
        "name": "Vegetarian",
        "description": "No meat, may include eggs/dairy",
    },
    "gluten_free": {
        "name": "Gluten-free",
        "description": "Free from wheat, barley, etc.",
    },
    "high_protein": {
        "name": "High protein",
        "description": "Protein-rich, for athletes",
    },
    "low_carb": {
        "name": "Low carb",
        "description": "Keto-friendly meals",
    },
    "traditional": {
        "name": "Traditional",
        "description": "Classic and cultural dishes",
    },
    "experimental": {
        "name": "Experimental",
        "description": "Creative and unusual combinations",
    },
    "children_friendly": {
        "name": "Children-friendly",
        "description": "Mild flavors, simple, no spicy stuff",
    },
    "spicy": {
        "name": "Spicy",
        "description": "Hot and spicy flavors",
    },
    "breakfast": {
        "name": "Breakfast",
        "description": "Morning meals",
    },
    "lunch": {
        "name": "Lunch",
        "description": "Midday meals",
    },
    "dinner": {
        "name": "Dinner",
        "description": "Evening meals",
    },
    "dessert": {
        "name": "Dessert",
        "description": "Sweet treats and finales",
    },
}


def load_tags(apps, schema_editor):
    RecipeTag = apps.get_model("cookbook", "RecipeTag")

    for key in PREDEFINED_TAGS:
        RecipeTag.objects.get_or_create(key=key)


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(load_tags, reverse_code=migrations.RunPython.noop),
    ]
