# Generated by Django 5.2.3 on 2025-06-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook", "0003_load_predefined_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
